=== psiborg112/ScorePlayer/ScorePlayer/advancedscroller.dtd
<!ELEMENT advancedscroller (liminummode?, juanitamode?, tiled?, playhead?, scrollermodule?, vertical?)>
<!ELEMENT liminummode (middleduration, minfragment, maxfragment, minspeed, maxspeed, pauselength?)>
<!ELEMENT juanitamode (middleduration, minfragment, maxfragment, minspeed, maxspeed, pauselength?)>
<!ELEMENT middleduration (#PCDATA)>
<!ELEMENT minfragment (#PCDATA)>
<!ELEMENT maxfragment (#PCDATA)>
<!ELEMENT minspeed (#PCDATA)>
<!ELEMENT maxspeed (#PCDATA)>
<!ELEMENT pauselength (#PCDATA)>
<!ELEMENT tiled (tiles)>
<!ELEMENT playhead (rgb, image, align)>
<!ELEMENT rgb (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT scrollermodule (name, tiles?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tiles (#PCDATA)>
<!ELEMENT vertical (#PCDATA)>

=== psiborg112/ScorePlayer/ScorePlayer/Liminum/liminumprefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE advancedscroller SYSTEM "advancedscroller.dtd">
<advancedscroller>
	<liminummode>
		<middleduration>60</middleduration>
		<minfragment>3</minfragment>
		<maxfragment>6</maxfragment>
		<minspeed>1</minspeed>
		<maxspeed>1</maxspeed>
		<pauselength>0</pauselength>
	</liminummode>
</advancedscroller>

=== psiborg112/ScorePlayer/ScorePlayer/JuanitaNeilsen/juanitaprefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE advancedscroller SYSTEM "advancedscroller.dtd">
<advancedscroller>
	<juanitamode>
		<middleduration>60</middleduration>
		<minfragment>3</minfragment>
		<maxfragment>6</maxfragment>
		<minspeed>2</minspeed>
		<maxspeed>2</maxspeed>
		<pauselength>2</pauselength>
	</juanitamode>
</advancedscroller>
